name: GitHub Metrics Complete

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # Job 1 : MÃ©triques principales (gauche)
  left-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_padding: 6%, 10%
          filename: left-metrics.svg
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
  
  # Job 2 : Habits charts (droite)
  right-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: ""
          config_timezone: Europe/Paris
          filename: right-metrics.svg
          
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_charts_type: chart
          plugin_habits_trim: yes
          
          repositories_forks: yes
          repositories_affiliations: owner, collaborator

