name: GitHub Metrics Complete

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # Job 1 : Left Metrics
  left-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Paris
          config_padding: 6%, 10%
          filename: left-metrics.svg
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          use_prebuilt_image: yes
          experimental_features: --optimize-svg
  
  # Job 2 : Right Metrics
  right-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: repositories
          config_timezone: Europe/Paris
          config_padding: 6%, 10%
          filename: right-metrics.svg
          
          # Plugin Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          
          # Plugin Projects
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
          
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          use_prebuilt_image: yes
          experimental_features: --optimize-svg

