name: GitHub Metrics

on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  # Job 1 : Left Metrics
  left-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: header, activity, community, metadata
          config_timezone: Europe/Paris
          config_padding: 8%, 12%
          filename: left-metrics.svg
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          use_prebuilt_image: yes
  
  # Job 2 : Right Metrics
  right-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bonjour1000
          template: classic
          base: repositories
          config_timezone: Europe/Paris
          config_padding: 8%, 12%
          filename: right-metrics.svg
          
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          use_prebuilt_image: yes

